services:
  mysql:
    image: mysql:latest
    container_name: mysql_projetoaula06
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projetoaula06
      MYSQL_USER: user
      MYSQL_PASSWORD: coti
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network: